# Chapter 02 Data Frames — Exercise 11
## Bestsellers

Find the IDs and names of products that have sold more than the average.

## Exercise

Add your summary of the task and any dataset notes here.

In [1]:
import pandas as pd
from pandas import Series, DataFrame

df = pd.DataFrame([
    {'product_id': 23, 'name': 'computer', 'wholesale_price': 500, 'retail_price': 1000, 'sales': 100},
    {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35, 'retail_price': 75, 'sales': 1000},
    {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35, 'retail_price': 75, 'sales': 500},
    {'product_id': 15, 'name': 'banana', 'wholesale_price': 0.5, 'retail_price': 1, 'sales': 200},
    {'product_id': 87, 'name': 'sandwich', 'wholesale_price': 3, 'retail_price': 5, 'sales': 300},
    {'product_id': 24, 'name': 'phone', 'wholesale_price': 200, 'retail_price': 500, 'sales': None},
    {'product_id': 16, 'name': 'apple', 'wholesale_price': 0.5, 'retail_price': 1, 'sales': None},
    {'product_id': 17, 'name': 'pear', 'wholesale_price': 0.6, 'retail_price': 1.2, 'sales': None}
], index=[0, 1, 2, 3, 4, 5, 6, 7])

## Solution

In [4]:
# mean sales
df.loc[df['sales'] > df['sales'].mean(),
       ['product_id', 'name']]

   product_id            name
1          96  Python Workout
2          97  Pandas Workout

In [5]:
# query method
df.query('sales > sales.mean()')[['product_id', 'name']]

   product_id            name
1          96  Python Workout
2          97  Pandas Workout

## Beyond

In [6]:
# Beyond 1
"""
    Show the ID and name of products whose net income is 
    in the top 25% quantile
"""
df['net'] = df['retail_price'] - df['wholesale_price']
df.loc[df['net'] > df['net'].quantile(0.75),
        ['product_id', 'name']
       ]

   product_id      name
0          23  computer
5          24     phone

In [7]:
# Qeury method
df['net'] = df['retail_price'] - df['wholesale_price']
df.query('net > net.quantile(0.75)')[['product_id', 'name']]

   product_id      name
0          23  computer
5          24     phone

In [10]:
# Beyond 2
"""
    Show ID and name of products with lower-than-average sales
    numbers and whose wholesale price is greater than the average
"""
df.loc[(df['sales'] < df['sales'].mean()) &
       (df['wholesale_price'] > df['wholesale_price'].mean()),
       ['product_id', 'name']]

   product_id      name
0          23  computer

In [13]:
# query method
df.query('sales < sales.mean() &' \
'wholesale_price > wholesale_price.mean()')[['product_id','name']]

   product_id      name
0          23  computer

In [16]:
# Beyond 3
"""
    Show the name, wholesale and retail prices of products
    with IDs between 80 and 100 that sold fewer than 400 units
"""
df.loc[(df['product_id'] > 80) & (df['product_id'] < 100) & (df['sales'] < 400),
['name', 'wholesale_price', 'retail_price']]

       name  wholesale_price  retail_price
4  sandwich              3.0           5.0

In [17]:
# query method
df.query('product_id > 80 & product_id < 100 & sales < 400')[['name','wholesale_price', 'retail_price']]

       name  wholesale_price  retail_price
4  sandwich              3.0           5.0