# Chapter 02 Data Frames — Exercise 13
## Interpolation
When data contains missing values, we can remove any row containing even one missing value—but that may be too heavy-handed and may also remove useful data. One alternative is interpolation: replacing NaN with plausible values. The values may be wrong, but they will be roughly in the right ballpark.

In this exercise, we load some basic temperature data from New York City from the end of 2018 and the start of 2019. We then simulate a simple recurring equipment failure at 3:00 and 6:00 a.m. preventing us from getting temperature readings at those hours. How well does interpolation help us, and how far off are the interpolated mean and median calculations from the original, true values?

Here are the steps I want you to take:

1. Load the temperature data from New York City (from the nyc-temps.txt file) into a series. The measurements are in degrees Celsius.
2. Create a data frame with two columns: temp, with the temperatures, and hour, representing the hours at which the measurements were taken. The hour values should be 0, 3, 6, 9, 12, 15, 18, and 21, repeated for all 728 data points.
3. Calculate the mean and median values. These are the real values, which we hope to replicate via interpolation.
4. Set all values from 3:00 and 6:00 a.m. to NaN.
5. Interpolate the values with the interpolate method.
6. What are the mean and median of the interpolated data frame? Are they similar to the real values? Why or why not?

## Exercise

Add your summary of the task and any dataset notes here.

In [10]:
import pandas as pd
import numpy as np

s = pd.read_csv("C:/dev/Pandas-Workout/data/nyc-temps.txt").squeeze()
df = pd.DataFrame({'temp': s,
                'hour': [0,3,6,9,12,15,18,21] * 91})

In [11]:
# Get the mean + median for baseline data
df['temp'].describe()

count    728.000000
mean      -1.050824
std        5.026357
min      -14.000000
25%       -4.000000
50%        0.000000
75%        2.000000
max       12.000000
Name: temp, dtype: float64

In [12]:
# Set temp at 3 and 6 a.m. to NaN
df.loc[
    df['hour'].isin([3,6]), 'temp'
] = np.nan

In [ ]:
# Interpolate
df = df.interpolate()

In [13]:
df['temp'].describe()

count    546.000000
mean      -1.049451
std        5.027934
min      -14.000000
25%       -4.000000
50%        0.000000
75%        2.000000
max       12.000000
Name: temp, dtype: float64

## Beyond

Record what you learned or alternative approaches here.

1. How does the behavior of interpolate change if you use method='nearest'?
2. Let’s assume the equipment works fine around the clock but fails to record readings at –1 degrees and below. Are the interpolated values similar to the real (missing) values they replace? Why or why not?
3. A cheap solution to interpolation is to replace NaN values with the column’s mean. Do this (with the missing values from –1 and below), and compare the new mean and median. Again, why are (or aren’t) these values similar to the original ones?

In [14]:
# interpolate
"""

"""
df.interpolate(method='nearest').describe()

             temp        hour
count  728.000000  728.000000
mean    -1.050824   10.500000
std      5.026357    6.878589
min    -14.000000    0.000000
25%     -4.000000    5.250000
50%      0.000000   10.500000
75%      2.000000   15.750000
max     12.000000   21.000000

### Beyond 2

In [16]:
# reset our data
df = pd.DataFrame({'temp': s,
                'hour': [0,3,6,9,12,15,18,21] * 91})

In [17]:
# Remove values <= -1 to NaN
df.loc[df['temp'] <= -1, 'temp'] = np.nan

In [18]:
df = df.interpolate()

In [19]:
df['temp'].describe()

count    721.000000
mean       2.022191
std        2.345483
min        0.000000
25%        0.209524
50%        1.000000
75%        3.000000
max       12.000000
Name: temp, dtype: float64

In [21]:
# reset our data
df = pd.DataFrame({'temp': s, 
                'hour': [0,3,6,9,12,15,18,21] * 91})

# Remove values <= -1 to NaN
df.loc[df['temp'] <= -1, 'temp'] = np.nan

df = df.fillna(df.mean())

In [22]:
df.describe()

             temp        hour
count  728.000000  728.000000
mean     2.763926   10.500000
std      1.935689    6.878589
min      0.000000    0.000000
25%      2.000000    5.250000
50%      2.763926   10.500000
75%      2.763926   15.750000
max     12.000000   21.000000