# Chapter 02 Data Frames — Exercise 12
1. Create a data frame based on the individual series.
2. Calculate the IQR
3. Find the Outliers.
4. Use the outliers we have found to analyze passenger counts.

### Exercise

In [23]:
import pandas as pd
from pandas import Series, DataFrame

In [24]:
# Create the data frame based on the individual series.
"""
use `read_csv` to injest the csv file.
path to taxi distance.csv 'data/taxi-distance.csv'
path to taxi-passenger-count.csv 'data/taxi-distance.csv'
"""
# use absolute path.
trip_distance = pd.read_csv("C:/dev/Pandas-Workout/data/taxi-distance.csv", header=None).squeeze()
passenger_count = pd.read_csv("C:/dev/Pandas-Workout/data/taxi-passenger-count.csv", header=None).squeeze()

# use DataFrame
df = DataFrame({
    'trip_distance': trip_distance,
    'passenger_count':passenger_count
})
df.head(10)

   trip_distance  passenger_count
0           1.63                1
1           0.46                1
2           0.87                1
3           2.13                1
4           1.40                1
5           1.40                1
6           1.80                1
7          11.90                4
8           1.27                1
9           0.60                1

In [25]:
# iqr = df['trip_distance].quantile(0.75) - df['trip_distance'].quantile(0.25)
iqr = (
    df['trip_distance'].quantile(0.75) - 
    df['trip_distance'].quantile(0.25)
)
print(iqr)

2.3

In [26]:
# outlier distances --below
df[
    df['trip_distance'] < 
    df['trip_distance'].quantile(0.25) - 
    1.5*iqr
]

Empty DataFrame
Columns: [trip_distance, passenger_count]
Index: []

In [27]:
# outlier distances --above
df[df['trip_distance'] >
   df['trip_distance'].quantile(0.75) + 
   1.5 * iqr
]

      trip_distance  passenger_count
7             11.90                4
60             9.30                1
73            12.65                1
82            10.24                3
88            23.76                2
...             ...              ...
9975           7.60                1
9976          12.60                1
9979          11.30                1
9980           9.13                1
9982           9.30                1

[1219 rows x 2 columns]

In [28]:
# mean passenger count for outliers
df['passenger_count'][
    df['trip_distance'] > df['trip_distance'].quantile(0.75) +
    1.5*iqr
].mean()

np.float64(1.7301066447908122)

In [29]:
df['passenger_count'].mean()

np.float64(1.6594659465946595)

## Beyond

Questions after.

In [30]:
# lowest and highest 10% values
"""
How many outlier values were there?
"""
print(df[df['trip_distance'] > df['trip_distance'].quantile(0.9)])
print(df[df['trip_distance'] > df['trip_distance'].quantile(0.9)].mean())
print(df[df['trip_distance'] > df['trip_distance'].quantile(0.1)])
print(df[df['trip_distance'] > df['trip_distance'].quantile(0.1)].mean())

      trip_distance  passenger_count
7             11.90                4
60             9.30                1
73            12.65                1
82            10.24                3
88            23.76                2
...             ...              ...
9964          18.55                1
9976          12.60                1
9979          11.30                1
9980           9.13                1
9982           9.30                1

[999 rows x 2 columns]
trip_distance      13.304845
passenger_count     1.719720
dtype: float64
      trip_distance  passenger_count
0              1.63                1
2              0.87                1
3              2.13                1
4              1.40                1
5              1.40                1
...             ...              ...
9994           2.70                1
9995           4.50                1
9996           5.59                1
9997           1.54                6
9998           5.80                1

[8987 rows x 2 columns]
trip_distance      3.464800
passenger_count    1.663959
dtype: float64

In [32]:
# Beyond 2
"""
How many short, medium, and long trips were there for trips that had only one passenger? 
Note that data for passenger count and trip length are from the same data set, 
meaning that the indexes are the same.
"""
from scipy.stats import trimboth
trimboth(df['trip_distance'], 0.1)

array([0.63, 0.63, 0.63, ..., 8.2 , 8.2 , 8.2 ], shape=(8001,))

In [33]:
# Beyond 3
"""
The scipy.stats.zscore function rescales and centers (that is, normalizes) the data set. 
In this case, the mean is set to 0, and values can be above and below that value. 
Find all the distances for which the absolute value of the z-score is greater than 3.
"""
from scipy.stats import zscore
df['trip_distance'][abs(zscore(df['trip_distance'])) > 3]

88      23.76
238     18.32
379     16.38
509     16.82
641     19.72
        ...
9897    16.11
9899    17.48
9906    17.70
9955    15.49
9964    18.55
Name: trip_distance, Length: 306, dtype: float64